### ISSUE TITLE
PanZoom errors with series of different sizes

### ISSUE THREAD

**Issue by Erhannis** [halfhp/androidplot#19] opened 2016-11-29 18:53 UTC
When I have series with differing numbers of points, I get null pointer exceptions (and correspondingly glitchy graphics) when I try to zoom in.

E/com.androidplot.Plot: Exception while rendering Plot.
                        java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
                            at com.androidplot.xy.LineAndPointRenderer.renderPoints(LineAndPointRenderer.java:225)
                            at com.androidplot.xy.LineAndPointRenderer.drawSeries(LineAndPointRenderer.java:190)
                            at com.androidplot.xy.LineAndPointRenderer.onRender(LineAndPointRenderer.java:50)
                            at com.androidplot.xy.LineAndPointRenderer.onRender(LineAndPointRenderer.java:37)
                            at com.androidplot.ui.SeriesRenderer.render(SeriesRenderer.java:59)
                            at com.androidplot.xy.XYGraphWidget.drawData(XYGraphWidget.java:769)
                            at com.androidplot.xy.XYGraphWidget.doOnDraw(XYGraphWidget.java:458)
                            at com.androidplot.ui.widget.Widget.draw(Widget.java:347)
                            at com.androidplot.ui.LayoutManager.draw(LayoutManager.java:109)
                            at com.androidplot.Plot.renderOnCanvas(Plot.java:822)
                            at com.androidplot.Plot$1.run(Plot.java:390)
                            at java.lang.Thread.run(Thread.java:818)

Note that when I put a breakpoint there, conditional on p == null, inspecting `points` shows no nulls, which leads me to suspect threading issues.  On the other hand, I've put a breakpoint before the loop, and even inspecting `points` each time it stops there (each time showing no nulls) somehow I still get null pointer exceptions, which leads me to suspect debugger inconsistencies.

**Comment by halfhp** [comment] 2016-11-30 04:44
Are you on version 1.3 of the lib?

**Comment by Erhannis** [comment] 2016-12-01 18:54
Yes

**Comment by halfhp** [comment] 2016-12-02 15:34
are you doing any kind of modification to your series, ie. changing x/y vals on a background thread etc?

**Comment by Erhannis** [comment] 2016-12-02 18:06
Not once I start zooming.  I first load the view, then a little bit later some asynchronous tasks finish and put series on the plot.  Then I try zooming, and I get exceptions.

**Comment by halfhp** [comment] 2016-12-03 14:20
So far I've been unable to replicate the NullPointerException.  I did however find a couple potential bugs / optimizations while investigating which will be included in the 1.3.1 release going out a little later today.

Perhaps these fixes will help resolve the issues you are seeing, but I suspect there is still something else going on.   If you have a sample app or a list of changes I could make to one of the demo apps to replicate the issue it would be a huge help in tracking down what's going on here.

**Comment by halfhp** [comment] 2016-12-29 00:26
Closing for now since I cannot reproduce the issue. feel free to re-open with steps to reproduce.

**Closed by halfhp** 2016-12-29 00:26 UTC
Labels: cannot reproduce
