### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by Pascal66** [halfhp/androidplot#82] opened 2018-08-23 11:11 UTC
When I do :
implementation 'com.androidplot:androidplot-core:1.5.6'

With:
Android Studio 3.3 Canary 6
Build #AI-182.3684.101.33.4954005, built on August 15, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I can't compile :
Android resource compilation failed
C:\Users\Pascal\Desktop\PalIrri\palIrri\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4758: error: duplicate value for resource 'attr/backgroundColor' with config ''.
C:\Users\Pascal\Desktop\PalIrri\palIrri\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4758: error: resource previously defined here.

**Comment by Pascal66** [comment] 2018-08-27 13:11
28.0.1

**Comment by halfhp** [comment] 2018-08-27 23:09
Went through a few tests with setting up fresh projects. in a clean dev env etc. and couldnt find anything wrong.  I suspect it may be something in the Canary version of Android Studio.  Have you tried using the latest stable release of AS?

**Comment by halfhp** [comment] 2018-08-30 13:31
Closing for now as I cannot reproduce.  Feel free to reopen if you can verify that the problem you're experiencing exists in a non canary version of AS.

**Closed by halfhp** 2018-08-30 13:31 UTC
Labels: cannot reproduce
