### ISSUE TITLE
How to hide horizontal range lines on XYPlot ?

### ISSUE THREAD

**Issue by matdev** [halfhp/androidplot#75] opened 2018-03-06 15:04 UTC
Despite doing 
  
```
        mPlot.getGraph().setRangeGridLinePaint(null);
        mPlot.getGraph().setDomainGridLinePaint(null);

```
my bar chart's grid horizontal lines are still visibles.
I'm using style APDefacto.Dark

I've also asked the question here:
https://stackoverflow.com/questions/48620565/how-to-hide-horizontal-range-lines-on-androidplots-xyplot

**Comment by halfhp** [comment] 2018-03-06 17:11
Closing as not a bug.  You don't need to cross post here - I check for new SOF posts every morning :) (I don't always have time to respond though)

**Closed by halfhp** 2018-03-06 17:11 UTC
Labels: not a bug
